apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    set: master
  name: master-1
spec:
  clusterName: example
  bootstrap: {}
  version: 1.17.5
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraMachine
    name: master-1
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: master-1
spec:
  private:
    address: 172.31.12.204
    port: 22
  public:
    address: 54.67.75.253
    port: 22
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    set: worker
  name: worker-1
spec:
  clusterName: example
  bootstrap: {}
  version: 1.17.5
  infrastructureRef:
    apiVersion: cluster.weave.works/v1alpha3
    kind: ExistingInfraMachine
    name: worker-1
---
apiVersion: cluster.weave.works/v1alpha3
kind: ExistingInfraMachine
metadata:
  name: worker-1
spec:
  private:
    address: 172.31.29.183
    port: 22
  public:
    address: 54.219.183.94
    port: 22
